BTCUSD:
    scalbot:
        candle_frequency: 3
        patterns: [
            {'color': 'green', 'prev_color_1': 'green', 'prev_color_2': 'green', 'prev_color_3': 'red'},
            {'color': 'red', 'prev_color_1': 'red', 'prev_color_2': 'red', 'prev_color_3': 'green'},
        ]
    trading_strategy:
        bet_amount: 100
        risk: 0.01
        stop_loss: 0.0035
        take_profit_1: 0.0035
        take_profit_1_share: 0.40
        take_profit_2: 0.0060
        take_profit_2_share: 0.30
        take_profit_3: 0.0080
        take_profit_3_share: 0.30
DOTUSD:
    scalbot:
        candle_frequency: 3
        patterns: [
            { 'color': 'green', 'prev_color_1': 'green', 'prev_color_2': 'green', 'prev_color_3': 'red' },
            { 'color': 'red', 'prev_color_1': 'red', 'prev_color_2': 'red', 'prev_color_3': 'green' },
        ]
    trading_strategy:
        bet_amount: 25
        risk: 0.03
        stop_loss: 0.030
        take_profit_1: 0.030
        take_profit_1_share: 0.40
        take_profit_2: 0.050
        take_profit_2_share: 0.30
        take_profit_3: 0.075
        take_profit_3_share: 0.30
MANAUSD:
    scalbot:
        candle_frequency: 3
        patterns: [
            { 'color': 'green', 'prev_color_1': 'green', 'prev_color_2': 'green', 'prev_color_3': 'red' },
            { 'color': 'red', 'prev_color_1': 'red', 'prev_color_2': 'red', 'prev_color_3': 'green' },
        ]
    trading_strategy:
        bet_amount: 25
        risk: 0.015
        stop_loss: 0.0020
        take_profit_1: 0.0021
        take_profit_1_share: 0.4
        take_profit_2: 0.0042
        take_profit_2_share: 0.3
        take_profit_3: 0.0064
        take_profit_3_share: 0.3
